# Generated by Django 5.2.4 on 2025-07-17 09:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, help_text="Customer's full name", max_length=255, null=True)),
                ('phone_number', models.CharField(help_text="Customer's phone number (unique)", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (e.g., 9876543210).', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, help_text="Customer's email address", max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text="Customer's address", null=True)),
                ('store_credit_balance', models.DecimalField(decimal_places=2, default=0, help_text="Customer's store credit balance", max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='customer_name_idx'), models.Index(fields=['phone_number'], name='customer_phone_number_idx'), models.Index(fields=['created_at'], name='customer_created_at_idx'), models.Index(fields=['store_credit_balance'], name='customer_credit_idx')],
            },
        ),
    ]
