# Generated by Django 5.2.4 on 2025-09-21 15:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsncode',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('25.00'))]),
        ),
        migrations.AddField(
            model_name='hsncode',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hsncode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='hsncode',
            name='code',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='hsncode',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('40.00'))]),
        ),
    ]
