# Generated by Django 5.2.4 on 2025-09-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_hsncode_gsthsncode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gst_percentage',
        ),
    ]
