# Generated by Django 5.2.4 on 2025-09-21 18:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_product_gst_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsthsncode',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('40.00'))]),
        ),
    ]
