# Generated by Django 5.1.4 on 2025-11-14 10:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_gsthsncode_gst_percentage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_size_color',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_size_null_color',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_color_null_size',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_null_size_null_color',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Commission cannot be negative'), django.core.validators.MaxValueValidator(100, 'Commission cannot exceed 100%')]),
        ),
    ]
