# Generated by Django 5.1.4 on 2025-11-14 10:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_productvariant_unique_product_size_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Commission cannot be negative'), django.core.validators.MaxValueValidator(100, 'Commission cannot exceed 100%')]),
        ),
    ]
