# Generated by Django 5.1.4 on 2025-11-14 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='first_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_two',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (e.g., 9876543210).', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='second_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(blank=True, help_text="Supplier's GST Identification Number.", max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinvoice',
            unique_together={('supplier', 'invoice_number', 'invoice_date')},
        ),
    ]
