# Generated by Django 5.2.4 on 2025-09-06 14:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('ESTIMATE', 'Estimate'), ('QUOTATION', 'Quotation'), ('RECEIPT', 'Receipt'), ('STATEMENT', 'Account Statement')], default='INVOICE', max_length=20)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('LETTER', 'Letter'), ('LEGAL', 'Legal')], default='A5', max_length=10)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='INR', max_length=3)),
                ('show_logo', models.BooleanField(default=True, help_text='Show shop logo in header')),
                ('show_shop_name', models.BooleanField(default=True, help_text='Show shop name in header')),
                ('show_address', models.BooleanField(default=True, help_text='Show shop address in header')),
                ('show_contact', models.BooleanField(default=True, help_text='Show contact information in header')),
                ('show_gst', models.BooleanField(default=True, help_text='Show GST number in header')),
                ('show_invoice_number', models.BooleanField(default=True, help_text='Show invoice number')),
                ('show_date', models.BooleanField(default=True, help_text='Show invoice date')),
                ('show_due_date', models.BooleanField(default=True, help_text='Show due date (for credit invoices)')),
                ('show_payment_method', models.BooleanField(default=True, help_text='Show payment method')),
                ('show_customer_details', models.BooleanField(default=True, help_text='Show customer information')),
                ('show_item_description', models.BooleanField(default=True, help_text='Show item descriptions')),
                ('show_quantity', models.BooleanField(default=True, help_text='Show quantities')),
                ('show_unit_price', models.BooleanField(default=True, help_text='Show unit prices')),
                ('show_discount', models.BooleanField(default=True, help_text='Show discount information')),
                ('show_tax_breakdown', models.BooleanField(default=True, help_text='Show tax breakdown')),
                ('show_total', models.BooleanField(default=True, help_text='Show total amounts')),
                ('show_terms_conditions', models.BooleanField(default=True, help_text='Show terms and conditions')),
                ('show_qr_code', models.BooleanField(default=True, help_text='Show QR code for payments')),
                ('show_thank_you', models.BooleanField(default=True, help_text='Show thank you message')),
                ('show_signature', models.BooleanField(default=False, help_text='Show signature line')),
                ('terms_conditions', models.TextField(blank=True, help_text='Custom terms and conditions text', null=True)),
                ('thank_you_message', models.TextField(blank=True, help_text='Custom thank you message', null=True)),
                ('footer_note', models.TextField(blank=True, help_text='Additional footer note', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Report Configurations',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(help_text='Name of the shop/business', max_length=255)),
                ('first_line', models.CharField(help_text='First line of address (e.g., Building name, Street)', max_length=255)),
                ('second_line', models.CharField(blank=True, help_text='Second line of address (e.g., Area, Locality)', max_length=255, null=True)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state', models.CharField(help_text='State name', max_length=100)),
                ('pincode', models.CharField(help_text='PIN/ZIP code', max_length=10)),
                ('country', models.CharField(default='India', help_text='Country name', max_length=100)),
                ('gst_no', models.CharField(blank=True, help_text='GST Registration Number', max_length=15, null=True)),
                ('phone_number', models.CharField(help_text='Primary phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (e.g., 9876543210).', regex='^\\d{10}$')])),
                ('phone_two', models.CharField(blank=True, help_text='Secondary phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (e.g., 9876543210).', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, help_text='Business email address', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Business website URL', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Shop logo image', null=True, upload_to='shop_logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this shop details is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_details_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Details',
                'verbose_name_plural': 'Shop Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
