# Generated by Django 5.2.4 on 2025-10-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfiguration',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('58mm', '58mm'), ('LETTER', 'Letter'), ('LEGAL', 'Legal')], default='A5', max_length=10),
        ),
    ]
