# Generated by Django 5.2.4 on 2025-09-06 15:15

import base.utility
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField()),
                ('cart_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('original_invoice_no', models.CharField(blank=True, help_text='Original invoice number before conversion', max_length=50, null=True)),
                ('invoice_type', models.CharField(choices=[('GST', 'Gst'), ('CASH', 'Cash')], default='GST', max_length=20)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='UNPAID', max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total invoice amount before discount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount given to customer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount received in advance (only for credit invoices)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('UPI', 'UPI'), ('ONLINE_PAYMENT', 'Online Payment'), ('OTHER', 'Other')], default='CASH', max_length=25)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount paid against this invoice', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('financial_year', models.CharField(default=base.utility.get_financial_year, max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customer.customer')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mrp', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Maximum Retail Price / Actual Price', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual selling price per unit (after discount)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Cost price per unit (for profit calculation)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoice.invoice')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('GST', 'Gst'), ('CASH', 'Cash')], default='GST', max_length=20)),
                ('financial_year', models.CharField(max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['invoice_type', 'financial_year'], name='invoice_inv_invoice_3c3d82_idx')],
                'unique_together': {('invoice_type', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocation_created_by', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='invoice.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='customer.payment')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'payment_status'], name='invoice_inv_custome_fa39bf_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoice_inv_invoice_54f3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_status'], name='invoice_inv_payment_b380c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='invoice_inv_invoice_aeba30_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoice_inv_invoice_a9b80b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['financial_year'], name='invoice_inv_financi_1ba394_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_type', 'financial_year'], name='invoice_inv_payment_c44247_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoice_inv_due_dat_b8a0e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_type', 'CASH'), ('advance_amount__lte', django.db.models.expressions.CombinedExpression(models.F('amount'), '-', models.F('discount_amount'))), _connector='OR')), name='advance_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('amount'), '-', models.F('discount_amount')), '-', models.F('advance_amount')))), name='paid_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_type', 'CASH'), ('due_date__isnull', True), ('due_date__gte', models.F('invoice_date')), _connector='OR')), name='due_date_check'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('invoice_type', 'financial_year', 'sequence_no'), name='unique_invoice_sequence'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'product_variant'], name='invoice_inv_invoice_f48b71_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['product_variant'], name='invoice_inv_product_58ba49_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='invoice_inv_invoice_a010ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'product_variant')},
        ),
    ]
