# Generated by Django 5.2.4 on 2025-09-09 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='financial_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='AuditTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Audit session title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the audit session')),
                ('audit_type', models.CharField(choices=[('CONVERSION', 'Invoice Conversion'), ('RENUMBER', 'Invoice Renumbering')], default='CONVERSION', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of audit period')),
                ('end_date', models.DateField(help_text='End date of audit period')),
                ('financial_year', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_table_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('new_invoice_no', models.CharField(max_length=50)),
                ('reason', models.CharField(default='Invoice conversion', max_length=200)),
                ('change_type', models.CharField(choices=[('CONVERSION', 'Type Conversion'), ('RENUMBER', 'Number Change'), ('MODIFICATION', 'General Modification')], default='CONVERSION', max_length=20)),
                ('old_invoice_type', models.CharField(blank=True, max_length=20, null=True)),
                ('new_invoice_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_audits', to='invoice.audittable')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_audit_changes', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='invoice.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='audittable',
            index=models.Index(fields=['start_date', 'end_date'], name='invoice_aud_start_d_cc732d_idx'),
        ),
        migrations.AddIndex(
            model_name='audittable',
            index=models.Index(fields=['created_at'], name='invoice_aud_created_9648aa_idx'),
        ),
        migrations.AddIndex(
            model_name='audittable',
            index=models.Index(fields=['created_by'], name='invoice_aud_created_7b541b_idx'),
        ),
        migrations.AddIndex(
            model_name='audittable',
            index=models.Index(fields=['audit_type'], name='invoice_aud_audit_t_69a244_idx'),
        ),
        migrations.AddIndex(
            model_name='audittable',
            index=models.Index(fields=['status'], name='invoice_aud_status_58ef11_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceaudit',
            index=models.Index(fields=['invoice', 'created_at'], name='invoice_inv_invoice_e1788c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceaudit',
            index=models.Index(fields=['created_at'], name='invoice_inv_created_1ec873_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceaudit',
            index=models.Index(fields=['change_type'], name='invoice_inv_change__4f8fec_idx'),
        ),
    ]
