# Generated by Django 5.2.5 on 2025-08-17 18:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Amount received in advance (only for credit invoices)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
