# Generated by Django 5.2.4 on 2025-09-11 13:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('inventory', '0002_inventorylog'),
        ('invoice', '0002_alter_invoice_financial_year_audittable_invoiceaudit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, help_text='Auto-generated return invoice number', max_length=50, null=True, unique=True)),
                ('sequence_no', models.PositiveIntegerField(blank=True, null=True)),
                ('refund_type', models.CharField(choices=[('STORE_CREDIT', 'Store Credit'), ('CASH_REFUND', 'Cash Refund'), ('VOUCHER', 'Voucher'), ('EXCHANGE', 'Exchange'), ('OTHER', 'Other')], default='CASH_REFUND', help_text='Type of refund to be processed', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the return', max_length=20)),
                ('reason', models.CharField(choices=[('CUSTOMER_REQUEST', 'Customer Request'), ('STORE_POLICY', 'Store Policy'), ('DEFECTIVE_PRODUCT', 'Defective Product'), ('WRONG_PRODUCT', 'Wrong Product'), ('WRONG_SIZE', 'Wrong Size'), ('DAMAGED_IN_TRANSIT', 'Damaged in Transit'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], default='CUSTOMER_REQUEST', help_text='Reason for the return', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total return amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual amount to be refunded', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('restocking_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fee charged for restocking', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when return was initiated')),
                ('approved_date', models.DateTimeField(blank=True, help_text='Date when return was approved', null=True)),
                ('processed_date', models.DateTimeField(blank=True, help_text='Date when return was processed', null=True)),
                ('financial_year', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the return', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for staff only', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_invoices', to='customer.customer')),
                ('invoice', models.ForeignKey(help_text='Original invoice being returned', on_delete=django.db.models.deletion.CASCADE, related_name='return_invoices', to='invoice.invoice')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_modified_by', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_processed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantity being returned', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_original', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Original quantity from invoice', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Unit price at time of return', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total amount for this item', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('condition', models.CharField(choices=[('NEW', 'New/Unused'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective')], default='NEW', help_text='Condition of returned item', max_length=20)),
                ('return_reason', models.CharField(choices=[('CUSTOMER_REQUEST', 'Customer Request'), ('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item'), ('WRONG_SIZE', 'Wrong Size'), ('DAMAGED', 'Damaged in Transit'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], default='CUSTOMER_REQUEST', help_text='Reason for returning this specific item', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notes about this return item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_invoice_item', models.ForeignKey(blank=True, help_text='Original invoice item being returned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='invoice.invoiceitem')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_invoice_items', to='inventory.productvariant')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_invoice_items', to='invoice.returninvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['customer', 'status'], name='invoice_ret_custome_91a396_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['return_date'], name='invoice_ret_return__cd86fd_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['status'], name='invoice_ret_status_fa8bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['refund_type'], name='invoice_ret_refund__70e8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['financial_year'], name='invoice_ret_financi_c80900_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['invoice'], name='invoice_ret_invoice_d2c814_idx'),
        ),
        migrations.AddConstraint(
            model_name='returninvoice',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__lte', models.F('total_amount'))), name='refund_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='returninvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), ('processed_date__isnull', True), _connector='OR')), name='processed_date_check'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceitem',
            index=models.Index(fields=['return_invoice', 'product_variant'], name='invoice_ret_return__d3cb71_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceitem',
            index=models.Index(fields=['product_variant'], name='invoice_ret_product_64f781_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceitem',
            index=models.Index(fields=['condition'], name='invoice_ret_conditi_535b76_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceitem',
            index=models.Index(fields=['return_reason'], name='invoice_ret_return__72a8e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='returninvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_returned__lte', models.F('quantity_original'))), name='return_quantity_check'),
        ),
        migrations.AddConstraint(
            model_name='returninvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_returned__gt', Decimal('0'))), name='positive_return_quantity'),
        ),
    ]
