# Generated by Django 5.2.5 on 2025-08-17 18:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount received in advance (only for credit invoices)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount given to customer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
