# Generated by Django 5.2.4 on 2025-09-11 15:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_returninvoice_returninvoiceitem_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='returninvoiceitem',
            name='positive_return_quantity',
        ),
        migrations.AlterField(
            model_name='returninvoiceitem',
            name='quantity_returned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantity being returned', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
