# Generated by Django 5.2.4 on 2025-09-21 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('invoice', '0004_remove_returninvoiceitem_positive_return_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='returninvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('invoice',), name='unique_pending_return_per_invoice'),
        ),
    ]
