# Generated by Django 5.2.4 on 2025-09-21 18:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_gsthsncode_gst_percentage'),
        ('invoice', '0005_returninvoice_unique_pending_return_per_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_type',
            field=models.CharField(choices=[('CGST_SGST', 'CGST/SGST'), ('IGST', 'IGST')], default='CGST_SGST', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cess rate', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='GST percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='inventory.gsthsncode'),
        ),
    ]
