# Generated by Django 5.1.4 on 2025-11-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_gst_type_invoiceitem_cess_rate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together=set(),
        ),
    ]
