# Generated by Django 5.2.4 on 2025-09-06 15:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('invoice', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('SALE', 'Sale'), ('RETURN', 'Customer Return'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('DAMAGE', 'Mark as Damaged'), ('INITIAL', 'Initial Stock')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Selling price at time of transaction', max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit for sale transactions', max_digits=12, null=True)),
                ('allocated_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='For SALE transactions: quantity allocated from source_inventory_log', max_digits=12, null=True)),
                ('remaining_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='For STOCK_IN/INITIAL: remaining quantity available for allocation', max_digits=12, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total value of the transaction', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
                ('invoice_item', models.ForeignKey(blank=True, help_text='Customer invoice item for sale transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='invoice.invoiceitem')),
                ('source_inventory_log', models.ForeignKey(blank=True, help_text='For SALE transactions: points to the STOCK_IN/INITIAL log this sale is allocated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_sales', to='inventory.inventorylog')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='supplier.supplierinvoice')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['variant', 'timestamp'], name='inventory_i_variant_1320cc_idx'), models.Index(fields=['transaction_type', 'timestamp'], name='inventory_i_transac_14c4f1_idx'), models.Index(fields=['created_by', 'timestamp'], name='inventory_i_created_e7a15d_idx')],
            },
        ),
    ]
