# Generated by Django 5.2.4 on 2025-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the UOM, e.g., Piece, Dozen, Meter', max_length=50)),
                ('short_code', models.CharField(help_text='Abbreviation for the UOM, e.g., pcs, doz, m', max_length=10, unique=True)),
                ('category', models.CharField(help_text='Type of UOM, e.g., Quantity, Weight, Length, Volume', max_length=50)),
                ('base_unit', models.BooleanField(default=False, help_text='Marks if this is the base unit for conversions')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='Factor to convert to base unit (e.g., 1 dozen = 12 pcs)', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Optional notes about this UOM', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this UOM is active or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit of Measurement',
                'verbose_name_plural': 'Units of Measurement',
            },
        ),
    ]
