# Generated by Django 5.2.4 on 2025-09-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_hsncode_cess_rate_hsncode_effective_from_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HsnCode',
            new_name='GSTHsnCode',
        ),
    ]
